apiVersion: configuration.pipeline-service.io/v1alpha1
kind: SettingsConfig
health:
  healthProbeBindAddress: :8081
metrics:
  bindAddress: 127.0.0.1:8080
webhook:
  port: 9443
leaderElection:
  leaderElect: true
  resourceName: 67a0541b.pipeline-service.io
namespace: settings-ps-controller
networkPolicyConfig:
  spec:
    podSelector:
      matchLabels:
        pipeline-service.io/network-isolation: "true"
    policyTypes:
    - Ingress
    - Egress

