---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apis.kcp.dev
  resources:
  - apibindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apis.kcp.dev
  resources:
  - apibindings/finalizers
  verbs:
  - update
- apiGroups:
  - apis.kcp.dev
  resources:
  - apibindings/status
  verbs:
  - get
- apiGroups:
  - apis.kcp.dev
  resources:
  - apiexports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - configuration.pipeline-service.io
  resources:
  - settings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - configuration.pipeline-service.io
  resources:
  - settings/finalizers
  verbs:
  - update
- apiGroups:
  - configuration.pipeline-service.io
  resources:
  - settings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies/status
  verbs:
  - get
  - patch
  - update
