# permissions for end users to view settings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: settings-viewer-role
rules:
- apiGroups:
  - configuration.pipeline-service.io
  resources:
  - settings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - configuration.pipeline-service.io
  resources:
  - settings/status
  verbs:
  - get
