# permissions for end users to edit settingsconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: settingsconfig-editor-role
rules:
- apiGroups:
  - configuration.pipeline-service.io
  resources:
  - settingsconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - configuration.pipeline-service.io
  resources:
  - settingsconfigs/status
  verbs:
  - get
