# permissions for end users to edit widgets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: widget-editor-role
rules:
- apiGroups:
  - configuration.pipeline-service.io
  resources:
  - widgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - configuration.pipeline-service.io
  resources:
  - widgets/status
  verbs:
  - get
