apiVersion: apis.kcp.dev/v1alpha1
kind: APIBinding
metadata:
  name: settings-configuration.pipeline-service.io
spec:
  reference:
    workspace:
      exportName: settings-configuration.pipeline-service.io
      path: root:pipeline-service:management
  permissionClaims:
  - group: "networking.k8s.io"
    resource: networkpolicies
    state: Accepted
    # identityHash needs to match the export of the workload cluster
    # it can be set with: make patch-identity
    identityHash: "deb840285bd53330ec748ff846caff64f93a4ad1451bc3ca7531b4f62bb50246"
  - group: ""
    resource: secrets
    state: Accepted
  - group: ""
    resource: configmaps
    state: Accepted
