apiVersion: apis.kcp.dev/v1alpha1
kind: APIBinding
metadata:
  name: settings-configuration.pipeline-service.io
spec:
  reference:
    workspace:
      exportName: settings-configuration.pipeline-service.io
      # TODO: the path needs to match the location of the apiexport
      path: root:pipeline-service:management
  permissionClaims:
  - group: "apis.kcp.dev"
    resource: "apibindings"
    state: Accepted
  - group: "networking.k8s.io"
    resource: networkpolicies
    state: Accepted
    # identityHash needs to match the export of the workload cluster
    # it can be set with: make patch-identity
    identityHash: "493408fea0d2b0f7a0665fbeac4c67a43adc8d149dea4a48711028e967d6fd5c"
  - group: ""
    resource: "namespaces"
    state: Accepted
