apiVersion: apis.kcp.dev/v1alpha1
kind: APIBinding
metadata:
  name: settings-configuration.pipeline-service.io
spec:
  reference:
    workspace:
      exportName: settings-configuration.pipeline-service.io
      path: root:pipeline-service:management
  acceptedPermissionClaims:
  - group: "networking.k8s.io"
    resource: networkpolicies
    # identityHash needs to match the export of the workload cluster
    # it can be set with: make patch-identity
    identityHash: "45fb988f70adb07a383f5badee360340222be6aa7af3a46a2f18b2a6ec87ce3f"
  - group: ""
    resource: secrets
  - group: ""
    resource: configmaps
