apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  name: configuration.pipeline-service.io
spec:
  latestResourceSchemas:
    - today.widgets.configuration.pipeline-service.io
  permissionClaims:
  - group: ""
    resource: secrets
  - group: ""
    resource: configmaps
