apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  name: configuration.pipeline-service.io
spec:
  latestResourceSchemas:
    - today.settings.configuration.pipeline-service.io
  permissionClaims:
  - group: "apis.kcp.dev"
    resource: "apibindings"
  - group: "networking.k8s.io"
    resource: networkpolicies
    # identityHash needs to match the export of the workload cluster
    # it can be set with: make patch-identity 
    identityHash: "a1171f89c2274572ac14ee99f6f733069ae14ce41db83ba550da58e8f4802b72"
  - group: ""
    resource: "resourcequotas"
  - group: ""
    resource: "namespaces"
